development:
  adapter: postgresql
  encoding: unicode
  database: my_keyboards_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: my_keyboards_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: my_keyboards_production
  pool: 5
  username:
  password:
